mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('celulas/', include('celulas.urls')),
    path('membros/', include('membros.urls')),
    path('contribuicoes/', include('contribuicoes.urls')),
    path('reunioes/', include('reunioes.urls')),
    path('visitantes/', include('visitantes.urls')),
    path('salas/', include('salas.urls')),
    path('matriz/', include('matriz.urls')),
    path('despesas/', include('despesas.urls')),
    path('missoes/', include('missao.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salas/urls.py
from django.urls import path
from .views import SalasCreate, SalasList, SalasUpdate, SalasDelete, SalasView, GerarPDFSalas
from .views_ajax import buscar_alunos

urlpatterns = [
    path('buscar-alunos/', buscar_alunos, name='buscar-alunos'),
    path('Salas/', SalasCreate.as_view(), name='salas-list'),
    path('', SalasList.as_view(), name='listar-salas'),
    path('editar/<int:pk>/', SalasUpdate.as_view(), name='editar-sala'),
    path('excluir/<int:pk>/', SalasDelete.as_view(), name='excluir-sala'),
    path('ver/<int:pk>/', SalasView.as_view(), name='ver-sala'),
    path('gerar_pdf/', GerarPDFSalas.as_view(), name='gerar-pdf-salas'),
    path('cadastrar/', SalasCreate.as_view(), name='cadastrar-sala'),  # Adicionando a URL para cadastrar-sala
]

visitantes/urls.py
from django.urls import path
from .views import VisitantesCreate, VisitantesDelete, VisitantesList, VisitantesUpdade, VisitantesView

urlpatterns = [
   # path('endereço/', MinhaView.as_view(), name = "Nome-da-url"),
   path('cadastrar/visitantes', VisitantesCreate.as_view(), name = "cadastrar-visitantes"),
   path('editar/visitantes/<int:pk>', VisitantesUpdade.as_view(), name =  'editar-visitantes'),
   path('excluir/visitantes/<int:pk>', VisitantesDelete.as_view(), name =  'excluir-visitantes'),
   path('visualizar/visitantes/<int:pk>', VisitantesView.as_view(), name =  'visualizar-visitantes'),
   path('listar/visitantes', VisitantesList.as_view(), name =  'listar-visitantes'),
]

visitantes/models.py
from django.db import models

class Visitantes(models.Model):
    data = models.DateField(verbose_name="Data da visita", null=True, blank=True)
    nome = models.CharField(max_length=50, unique=True, blank=False)  # Nome obrigatório
    endereco = models.CharField(max_length=100, verbose_name="Endereço", blank=True, null=True)
    filhos = models.CharField(max_length=16, verbose_name="Quantidade de filhos", blank=True, null=True)
    telefone = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self):
        return "{}(Visitante)".format(self.nome)





visitantes/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.exceptions import PermissionDenied
from .models import Visitantes
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from braces.views import GroupRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class VisitantesCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    group_required = u"Administradores", u"Secretaria", u"Pastor", u"Diacono", u"Presbitero"
    model = Visitantes
    fields = ['nome', 'data', 'endereco', 'telefone', 'filhos']
    template_name = 'visitantes/form.html'
    success_url = reverse_lazy('listar-visitantes')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Cadastro de visitantes"
        context['botao'] = "Cadastrar"
        
        return context

class VisitantesUpdade(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    group_required = u"Administradores", u"Secretaria"
    model = Visitantes
    fields = ['nome', 'data', 'endereco', 'telefone', 'filhos']
    template_name = 'visitantes/form.html'
    success_url = reverse_lazy('listar-visitantes')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Editar celula"
        context['botao'] = "Salvar"
        
        return context

class VisitantesDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    group_required = u"Administradores", u"Secretaria"
    model = Visitantes
    template_name = 'visitantes/form-excluir.html'
    success_url = reverse_lazy('listar-visitantes')

class VisitantesList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    group_required = u"Administradores", u"Secretaria", u"Pastor", u"Diacono", u"Presbitero"
    model = Visitantes
    template_name = 'visitantes/listas/visitantes-list.html'
    paginate_by = 5


    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied("Você precisa estar autenticado para acessar este módulo.")

        if request.user.is_superuser:
            return super().dispatch(request, *args, **kwargs)

        if not hasattr(request.user, 'perfil'):
            raise PermissionDenied("Seu perfil não está configurado corretamente.")

        if not request.user.perfil.acesso_visitantes:
            raise PermissionDenied("Você não tem permissão para acessar este módulo.")

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        txt_nome = self.request.GET.get('nome')
        if txt_nome:
            visitantes = Visitantes.objects.filter(nome__icontains=txt_nome)
        else:
            visitantes = Visitantes.objects.all()
        return visitantes

class VisitantesView(GroupRequiredMixin, LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('login')
    group_required = u"Administradores", u"Secretaria"
    template_name = 'visitantes/visualizar.html'
    model = Visitantes
    context_object_name = 'visitantes'


visitantes/templates/visitantes/form-excluir.html
{% extends 'paginas/modelo.html' %}

{% load static%}

{% block conteudo %}
    <h2>Excluir Visitantes</h2>
    <p>Confirme para excluir definitivamente.</p>
    <hr>
    <p> Deseja excluir o registro <strong>{{ object }}</strong>?</p>
    <form action="" method="POST">

        {% csrf_token %}


        {{ form.as_p }}

        <button class="btn btn-success float-right" type="submit">Excluir</button>
        <a href="{% url 'listar-visitantes' %}" class="btn btn-danger float-left">Cancelar</a>


    </form>

{% endblock %}

visitantes/templates/visitantes/form.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
    <h2> {{ titulo }}</h2>
    <p>Preencha todos os campos obrigatórios.</p>
    <hr>

    <form action="" method="POST">

        {% csrf_token %}


        {{ form|crispy }}

        <a href="{% url 'listar-visitantes' %}" class="btn btn-danger float-left">Cancelar</a>
        <button class="btn btn-success float-right" type="submit">{{ botao }}</button>
        

    </form>

{% endblock %}

{% block scripts %}

<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function () {
        $('#id_data').mask('00/00/0000', {placeholder: "__/__/____"});
        $('#id_filhos').mask('00', {placeholder: "--"});

        var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);       
    });
</script>

{% endblock %}

visitantes/templates/visitantes/visualizar.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block conteudo %}
    <h2>Dados do(a) visitante</h2>
    <p>Mais detalhes sobre a visita do dia <strong>{{visitantes.data}}</strong>.</p>
    <hr>

    <form>
        <div class="form-group">
          <label for="formGroupExampleInput">Nome</label>
          <input type="text" class="form-control" value="{{visitantes.nome}}" readonly>
        </div>
        <div class="form-group">
          <label for="formGroupExa">Data da visita</label>
          <input type="data" class="form-control" id="formGroupExa" value="{{visitantes.data}}" readonly>
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Endereço</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" value="{{visitantes.endereco}}" readonly>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput3">Telefone</label>
            <input type="text" class="form-control" id="formGroupExampleInput3" value="{{visitantes.telefone}}" readonly>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Quantidade de filhos</label>
            <input type="text" class="form-control" id="formGroupExampleInput2" value="{{visitantes.filhos}}" readonly>
        </div>
    <a href="{% url 'listar-visitantes' %}" class="btn btn-danger float-right">Voltar</a>
</form>

{% endblock %}